version: "3"

services:

  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    ports:
      - 9200:9200
    environment:
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    ports: 
      - 5601:5601
